const CONFIG = {
    introTitle: 'Hello babe à!',
    introDesc: `Trái đất vốn lạ thường,
    Mà sao em cứ đi nhầm đường,
    Lạc vào tim anh lẻ loi,
    Đằng sau chữ yêu đây là thương`,
    btnIntro: 'HiHi',
    title: 'Phải chăng em đã yêu ngay từ cái nhìn đầu tiên 😙',
    desc: 'Phải chăng em đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'Vẫn cứ là thích anh iuiu ❤💕❤',
    btnNo: 'Không, Anh à 😢😢😢',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh ❤',
    btnReply: 'Gửi cho anh ❤',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘😘',
    messDesc: 'Tối nay 7h anh qua đón nhé công chúa.',
    btnAccept: 'Okiiiii lun 💕💕💕',
    messLink: 'https://www.facebook.com/messages/t/101254904604257',
}